### ISSUE TITLE
Plop "ignore syntax" not functional for Github Actions Secrets

### ISSUE THREAD

**Issue by benmorehouse** [plopjs/plop#376]
# What 

I want to use plop to template some github actions files. Within github actions, you can include secrets that are provisioned through the UI in your workflow files. I am trying to template this out, but it doesn't seem like plop likes when we try to ignore these lines that start with `${{`, which is standard github actions syntax. 

# Input 

```
jobs:
  {{kebabCase name}}-test:
    name: Test {{kebabCase name}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Internal testing
      uses: ./packages/{{kebabCase name}}/ci/test
      with:
        ACTIONS_CUSTOM_TOKEN: {{{ ${{ secrets.ACTIONS_CUSTOM_TOKEN }} }}}
        SLACK_WEBHOOK_URL: {{{ ${{ secrets.SLACK_WEBHOOK_URL }} }}}
```

# Expected Output 

```yaml
jobs:
  example-test:
    name: Test example
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Internal testing
      uses: ./packages/example/ci/test
      with:
        ACTIONS_CUSTOM_TOKEN: ${{ secrets.ACTIONS_CUSTOM_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

# Received Output 

```sh
? What is the name of your package? example
? Please provide a short description of your package.
✖  +! Parse error on line 24:
...NS_CUSTOM_TOKEN: {{{${{ secrets.ACTIONS_
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
✖  ++ ../../../.github/workflows/{{snakeCase name}}_publish.yaml Aborted due to previous action failure
✖  ++ ../../../.github/workflows/{{snakeCase name}}_test.yaml Aborted due to previous action failure
```

# Proposal 

Add the ability to be able to check in the specific scenario if something has the `${{` prefix within `{{{` ignore brackets, and if so, treat it correctly.
